config/routes.rb
Project3::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :pages

  resources :groups

  resources :messages

  resources :users

  match 'users' => 'users#index'
  match 'messsages/users' => 'users#index'
  match 'groups/users' => 'users#index'

  match 'messages' => 'messages#index'
  match 'users/messages' => 'messages#index'
  match 'groups/messages' => 'messages#index'

  match 'groups' => 'groups#index'
  match 'users/groups' => 'groups#index'
  match 'messages/groups' => 'groups#index'

  match 'pages_editNiceThings' => 'pages#editNiceThings'
  match 'pages_viewGroup' => 'pages#viewGroup'
  match 'pages_joinGroup' => 'pages#joinGroup'
  match 'home' => 'pages#index'
  
  match '/auth/:provider/callback' => 'omniauth_callbacks#facebook'
  
  match 'download' => 'messages#download'

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'pages#index'

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :users, :class_name => 'User'


  attr_accessible :admin_key, :location, :name, :messages_released, :founder_username

  validates :name, :presence => true, :uniqueness => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.founder_username = current_user.name
    User.where(:name == @group.founder_username).first.is_admin = true
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <%if @group.founder_username == current_user.name%>
    <div class="field">
      <%= f.label :'Release the messages?' %><br />
      <%= f.check_box :messages_released %>
    </div>
  <% end %>

<p>
  <b>Users</b>
  <% @group.users.each do |user|   %>
  <tr>
    <td><%= link_to user.name, user_path(user) %></td>
  </tr>
  <% end %>
</p>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td style="padding-right:10px;"><%= group.name %></td>
    <td style="padding-right:10px;"><%= group.location %></td>
    <td  style="padding-right:10px;"><%= button_to 'Show', group, :class => "btn btn-info btn-mini",  :method => :get %></td>
    <%if current_user.group.name == group.name%>
      <td  style="padding-right:10px;"><%= button_to 'Edit', edit_group_path(group), :class => "btn btn-primary btn-mini", :method => :get %></td>
      <td><%= button_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-mini",  :method => :get %> </td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'Create Group', new_group_path, :class => "btn btn-success btn-mini",  :method => :get %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Location:</b>
  <%= @group.location %>
</p>

<p>
  <b>Users</b>
  <% @group.users.each do |user|   %>
  <tr>
    <td><%= link_to user.name, user_path(user) %></td>
  </tr>
  <% end %>
</p>



<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>