config/routes.rb
Project3::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :pages

  resources :groups

  resources :messages

  resources :users

  match 'users' => 'users#index'
  match 'messsages/users' => 'users#index'
  match 'groups/users' => 'users#index'

  match 'messages' => 'messages#index'
  match 'users/messages' => 'messages#index'
  match 'groups/messages' => 'messages#index'

  match 'groups' => 'groups#index'
  match 'users/groups' => 'groups#index'
  match 'messages/groups' => 'groups#index'

  match 'pages_editNiceThings' => 'pages#editNiceThings'
  match 'pages_viewGroup' => 'pages#viewGroup'
  match 'pages_joinGroup' => 'pages#joinGroup'
  match 'home' => 'pages#index'
  
  match '/auth/:provider/callback' => 'omniauth_callbacks#facebook'
  
  match 'download' => 'messages#download'

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :group, :is_admin, :key, :name, :group_id, :email, :password, :password_confirmation, :remember_me, :provider, :uid, :image_url

  has_many :messages, :class_name => 'Message'
  belongs_to :group

  validates :name, :presence => true
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name: auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid: auth.uid,
                         email: auth.info.email,
                         password: Devise.friendly_token[0,20],
                         image_url: auth.info.image
                         )
    end
    user
  end
  
  #In case the user already exists before signup
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%if current_user == @user%>
    <%= render 'form' %>
<%else%>
    <b>You are not this user. Don't try to edit him!<b>
<%end%>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Group</th>
    <th>Group ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
   <td  style="padding-right:10px;"><%= user.name %></td>
    <td  style="padding-right:10px;">
    	<% unless user.group.nil? %>
    		<%= user.group.name %>
    	<% end %>
    <td  style="padding-right:10px;"><%= user.group_id %></td>
    </td>
    <td  style="padding-right:10px;"><%= button_to 'Show', user, :class => "btn btn-info btn-mini",  :method => :get %></td>
    <%if current_user == user%>
        <td  style="padding-right:10px;"><%= button_to 'Edit', edit_user_path(user), :class => "btn btn-primary btn-mini",  :method => :get %></td>
        <td  style="padding-right:10px;"><%= button_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-mini",  :method => :get %></td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Group:</b>
  <% if @user.group != nil %>
      <%= @user.group.name%>
      <br/>
      <br/>
      
       <b>Group Members</b>
       <br/>
      <% @user.group.users.each do |u| %>
      <tr>
        <%= link_to u.name, user_path(u) %>
      </tr>
      <br/>
      <% end %>

  <% else %>
    Not in a group yet!
  <% end  %>

</p>

<%if current_user == @user%>
    <p>
    	<b>Recieved Messages</b>
    <br/>
    	<% @user.messages.each do |m| %>
      <tr>
      <%= link_to m.title, message_path(m) %>
    <br/>
    </tr>
  <% end %>
</p>
<%else%>
    <b>You cannot view this user's messages!</b>
<%end%>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>