config/routes.rb
Project3::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :pages

  resources :groups

  resources :messages

  resources :users

  match 'users' => 'users#index'
  match 'messsages/users' => 'users#index'
  match 'groups/users' => 'users#index'

  match 'messages' => 'messages#index'
  match 'users/messages' => 'messages#index'
  match 'groups/messages' => 'messages#index'

  match 'groups' => 'groups#index'
  match 'users/groups' => 'groups#index'
  match 'messages/groups' => 'groups#index'

  match 'pages_editNiceThings' => 'pages#editNiceThings'
  match 'pages_viewGroup' => 'pages#viewGroup'
  match 'pages_joinGroup' => 'pages#joinGroup'
  match 'home' => 'pages#index'
  
  match '/auth/:provider/callback' => 'omniauth_callbacks#facebook'
  
  match 'download' => 'messages#download'

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nice Things</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div class="container">
 <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
  <div class="container">
    <a class="brand" href="/">NT</a>
    <ul class="nav">
      <li class="divider-vertical"></li>
      <li class><%= link_to 'New Message', new_message_path %></li>
      <li class="divider-vertical"></li>
      <!--<li class><%= link_to 'Edit', pages_editNiceThings_path %></li>
      <li class="divider-vertical"></li>-->
      <li class><%= link_to 'Group', pages_viewGroup_path %></li>
      <li class="divider-vertical"></li>
      <li class><%= link_to 'Users', users_path %></li>
      <li class="divider-vertical"></li>
      <li><%= link_to 'Groups', groups_path %></li>
      <li class="divider-vertical"></li>
      <li><%= link_to 'Inbox', messages_path %></li>
      <li class="divider-vertical"></li>
    </ul>
    <div class="navbar-text pull-right">
      <% if user_signed_in? %>
      	Signed in as <%= current_user.name %>
      <% end %>
      </div>
    <ul class="nav pull-right">
      <li>
   	<% if user_signed_in? %>
    	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  	<% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
   	<% end %>
  </li>
    </ul>
  </div>
  </div>
</div>
<div style="margin-top:40px;">
	<% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
  
	<%= yield %>
</div>

   <footer>
      <div class="container">
        <hr>
        <p>&copy; Team 10 | Keith Pattison | Travis Williamson | Paul Unger        </p>
        
      </div>
    </footer>


 </div>

</body>
</html>